name: Android CI

on:
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  quality:
    name: Quality
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: ./gradlew lint
  test:
    name: Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  apk:
    name: Build APK
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: ./gradlew assembleDebug
